source('./CropProduction_module/Functions/Crop_acreage_distribution.R')
source('./CropProduction_module/Functions/fodder_NonDairy_functions.R')

## ---------------- NON-DAIRY FODDER AND CONCENTRATE N FEEDING ---------------- ##
## -----------------------------------------------------------------------------##

# STEPWISE METHODS
  # 1 - CALCULATE TOTAL N FEEDING INTAKE FROM SERRA ET AL 2019 AND OENEMA ET AL 2014
  # 2 - ALLOCATE TO NON-BOVINE ANIMALS
    # N INTAKE = N CONCENTRATE FOR POULTRY, PIGS AND RABBITS
    # N INTAKE = N ROUGHAGE FOR EQUIDES, SHEEP AND GOATS
  # 3 - CALCULATE N INTAKE FROM CONCENTRATE FEEDING FROM NONDAIRY BOVINE CATTLE
    # 3.1 - CALCULATE DMI AND ASSUME THAT 10% FO THE DMI IS SATISFIED BY N CONCENTRATES
    # 3.2 - CALCULATE N INTAKE FROM CONCENTRATES BY ASSUMING A N CONTENT OF KG N TONNES DM-1
  # 4 - CALCULATE N INTAKE FROM ROUGHAGE FROM NONDAIRY BOVINE CATTLE
    # N ROUGHAGE = N INTAKE - N CONCENTRATE

# METHODS: 
  # DMI : IPCC (2006)
  # ALLOCATION PROCEDURE: SERRA ET AL 2018

# COMPUTE TOTAL N INTAKE FROM CONCENTRATE FEED
compute_totals_concentrate_N(year = 2009)

# COMPUTE TOTAL N INTAKE FROM ROUGHAGE FEED
compute_totals_roughage_N(year = 2009)

# COMPUTE CROP N ROUGHAGE REMOVAL RATE
# unit: kg N (crop area)-1 yr-1
compute_crop_roughageN_ha(year = 2009)